### ISSUE TITLE
LaTeX Warning: Unused global option(s):

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#166]
We are somehow setting options the wrong way because they get reported as a LaTeX warning with "LaTeX Warning: Unused global option(s):"

**Comment by kmccurley** [comment]
I'm still seeing this:
```
LaTeX Warning: Unused global option(s):                                                                               
    [version=final].   
```

**Comment by jwbos** [comment]
I cannot reproduce this. When I use our template file and try all possible optional flags I do not see any warnings. 
Can you share an example?
I just committed [4941600](https://github.com/IACR/latex/pull/169/commits/4941600efca9fa6e01589cacd48674a212cbaa93) where other options (besides `version`) are now muted as well.

**Comment by jwbos** [comment]
I managed to reproduce this in my Windows setup. 
A new fix is in 831ef17c2396709d60792591788861a9c0868aad ready for review.

**Comment by kmccurley** [comment]
I am still seeing this in the log for iacrdoc if I add version=final
